### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by avronr**
Opensource it.

No License means standard copyright laws apply.

### CODE REVIEW

**Comment by jefftriplett** [comment]
@williln how does a CC license sound?

**Comment by avronr** [comment]
For the content sure! I'm not sure about CC for the code running the website. :)

**Comment by williln** [comment]
@avronr Thanks for suggesting we add a license! There isn't a lot of code to the site since it's just Jekyll, so I think we're mostly talking about the content. 

@jefftriplett maybe https://creativecommons.org/licenses/by-sa/4.0/?

**Comment by jefftriplett** [comment]
@avronr thank you for pointing this out. We updated everything to CC BY-SA 4.0 to make it easy.

**Pull request closed without merging**
